name: Playwright Tests
on:
  # Tự động chạy test mỗi khi bạn push code lên nhánh main hoặc master
  push:
    branches: [ main, master ]
  # Tự động chạy test khi có người tạo Pull Request vào nhánh main hoặc master
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest # Chạy trên hệ điều hành Ubuntu ảo của GitHub
    steps:
    - uses: actions/checkout@v4 # Tải mã nguồn dự án của bạn từ GitHub về máy ảo

    - uses: actions/setup-node@v4 # Cài đặt môi trường Node.js trên máy ảo
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci # Cài đặt các thư viện trong package.json

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps # Tải trình duyệt ẩn và thư viện hệ thống đi kèm

    - name: Run Playwright tests
      run: npx playwright test # Chạy toàn bộ các file test

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4 # Tải file báo cáo kết quả test lên GitHub
      if: ${{ !cancelled() }} # Luôn luôn chạy bước này kể cả khi test bị Fail
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
